### ISSUE TITLE
locale standard

### ISSUE THREAD

**Issue by iamstarkov** [andrepolischuk/typographic-numbers#1]
what locale standard do you use?

I used [ISO 639](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)  for my typographic-quotes and you?

**Comment by andrepolischuk** [comment]
Only lang tags from iso 639, lang-region from rfc 5646

**Comment by iamstarkov** [comment]
did we end up with smth?

**Comment by andrepolischuk** [comment]
I thought you just asked. What do you want to know about locale in this plugin?

**Comment by iamstarkov** [comment]
sorry, I just want to be consistent with `locale` option in textr’s ecosystem. Because it’s the only one important option for now.

**Comment by iamstarkov** [comment]
can we have this issue open until we end up with smth in shuvalov-anton/textr#15 ?

**Comment by andrepolischuk** [comment]
Sure, I'll keep it open
