### ISSUE TITLE
Shouldn't touch card numbers

### ISSUE THREAD

**Issue by denysdovhan** [andrepolischuk/typographic-numbers#2]
I have a trouble with your package, because it touches card numbers.

If I have text with any card number, I'll get:

```js
numbers("Card: 5441 1686 1100 5540"); // => Card: 5,441 1,686 1,100 5,540
numbers("Card: 5441168611005540"); // => Card: 5,441,168,611,005,540
```

Can you fix this? You could use [credit-card-regex](https://www.npmjs.com/package/credit-card-regex) for matching credit card numbers, for example.

**Comment by andrepolischuk** [comment]
I can fix, but I don't understand how to resolve 5441168611005540 as not-card number. What do you think about this?

**Comment by denysdovhan** [comment]
maybe better to recognize `5441168611005540` as number and `5441 1686 1100 5540` as credit card?

**Comment by denysdovhan** [comment]
👍

**Comment by andrepolischuk** [comment]
Patched version is published to npm

**Comment by denysdovhan** [comment]
oh, nice work
